// =============================================================================
// MIKROSKOPISCHE BEFUNDE GROUPER - PROSTATA STANZEN
// =============================================================================

// Grouper für mikroskopische Befunde nach MII-Patho-Befund
Instance: CoreNeedleBiopsyMicroscopicGrouper
InstanceOf: MII_PR_Patho_Microscopic_Grouper
Usage: #example
Title: "Mikroskopische Befunde Grouper"
Description: "Gruppierung aller mikroskopischen Befunde der Prostatastanzen"
* status = #final
* category[laboratory-category] = $observation-category#laboratory
* code = $loinc#22635-7
* subject = Reference(Patient1)
* effectiveDateTime = "2024-01-17T10:00:00+01:00"
* performer = Reference(PathologistPractitioner)
* valueString = "Mikroskopische Befunde aller 12 Prostatastanzen"
* bodySite = $sct#41216001 "Prostatic structure (body structure)"

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason01)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN01)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis01)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason02)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN02)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis02)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp03)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText03)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason04)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN04)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis04)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp05)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText05)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason06)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN06)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis06)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason07)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN07)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis07)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp08)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText08)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason09)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN09)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis09)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp10)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText10)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPrimaerGleason11)
* derivedFrom[+] = Reference(CoreNeedleBiopsySekundaerGleason11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyProzentGleason11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGleasonGrading11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyVerhaeltnisPositiverStanzen11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumoranteil11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumorbefallinLaenge11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyPerineuraleInfiltration11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisinSamenblase11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyLymphovaskulaereInvasion11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyTumornachweisInFettgewebe11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyIntraduktalesKarzinom11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyASAP11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyHighGradePIN11)
* derivedFrom[+] = Reference(CoreNeedleBiopsyGranulomatoeseProstatitis11)

* derivedFrom[+] = Reference(CoreNeedleBiopsyHistoTyp12)
* derivedFrom[+] = Reference(CoreNeedleBiopsyMorphText12)

* note.text = "Mikroskopische Untersuchung der 12 Prostatastanzen: Adenokarzinom in 6 von 12 Stanzen nachgewiesen. Gleason Scores von 3+3=6 bis 4+5=9. Benigne Befunde in Stanzen 03, 05, 08, 10, 12. Detaillierte Findings für alle 16 Parameter pro Stanze implementiert."